### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by remon0329** [remon0329/MY-APP#23]
Issueベースの作成をしました！！
ご確認お願いします。

■Webアプリの概要
思い出深いゲームやハマったゲーム動画や、スレッドを投稿してもらい
色々な世代の人気なゲームからマイナーなゲームまで気軽に共有できるサービスです。

■1週間辺りの開発に向けられる時間
- 1週間あたり：18時間

■ProjectsのURL
https://github.com/users/remon0329/projects/2

■MVPリリースまで
- [ ] rails new
- [ ] Renderにデプロイ
- [ ] TOPページ（投稿一覧表示）
- [ ] ユーザー登録・ログイン機能
- [ ] 掲示板投稿機能
- [ ] コメント機能
- [ ] 曖昧検索機能 
- [ ] ユーザープロフィールページ

■MVP後
- [ ] いいね機能
- [ ] タグ機能
- [ ] Xでのシェア機能
- [ ] プライバシーポリシー
- [ ] 利用規約
- [ ] 通知機能
- [ ] パスワードリセット機能
- [ ] パスワード更新

■MVPレビュー依頼予定日
予定日：2024年12月31日

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
概ね良さそうです。
LGTMです！
